### ISSUE TITLE
"No libdef files found" when trying to install

### ISSUE THREAD

**Issue by k-one-o-two** [flow-typed/flow-typed#1663]
I'm trying to use Flow on my angular app, so
`flow-typed install angular@4.4.6`
but it fails with
```• Searching for 1 libdefs...
• rebasing flow-typed cache...
ERROR: Unable to rebase the local cache repo. Error rebasing the `master` branch of the following repo:
C:\Users\username\.flow-typed\repo

undefined

NOTE: Unable to rebase local cache! If you don't currently have internet connectivity, no worries -- we'll update the local cache the next time you do.

UNCAUGHT ERROR: Error: npm/random-js_v1.x.x: No libdef files found!
    at validationError (c:\Users\username\AppData\Roaming\npm\node_modules\flow-typed\dist\lib\validationErrors.js:14:11)
    at extractLibDefsFromNpmPkgDir$ (c:\Users\username\AppData\Roaming\npm\node_modules\flow-typed\dist\lib\npm\npmLibDefs.js:142:51)
    at tryCatch (c:\Users\username\AppData\Roaming\npm\node_modules\flow-typed\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (c:\Users\username\AppData\Roaming\npm\node_modules\flow-typed\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (c:\Users\username\AppData\Roaming\npm\node_modules\flow-typed\node_modules\regenerator-runtime\runtime.js:117:21)
    at tryCatch (c:\Users\username\AppData\Roaming\npm\node_modules\flow-typed\node_modules\regenerator-runtime\runtime.js:65:40)
    at invoke (c:\Users\username\AppData\Roaming\npm\node_modules\flow-typed\node_modules\regenerator-runtime\runtime.js:155:20)
    at c:\Users\username\AppData\Roaming\npm\node_modules\flow-typed\node_modules\regenerator-runtime\runtime.js:165:13
    at <anonymous>```

What am I doing wrong? I'm new to Flow, so I can misunderstand something: if so, sorry)

**Comment by GAntoine** [comment]
Not sure what's going on, I ran the command and got:

```
• Searching for 1 libdefs...
!! No libdefs found in flow-typed for the explicitly requested libdefs. !!

Consider using `flow-typed create-stub angular@4` to generate an empty libdef that you can fill in.
```

Could you try deleting the installed definition for `random-js`? FYI the latest angular definition is at `1.5.x`.

**Comment by k-one-o-two** [comment]
@GAntoine delete definition from where? It's not installed.
 latest angular definition is at 1.5.x -- wow, so I can't use Flow with modern Angular?

**Comment by GAntoine** [comment]
> delete definition from where? It's not installed.

Oh I see, is `random-js` a dependency of you project? As in, is it present in `package.json`?

> latest angular definition is at 1.5.x -- wow, so I can't use Flow with modern Angular?

What do you mean? The latest version on npm is `1.6.7`, just one minor version behind.

```
1.6.7 is the latest of 126 releases
```

**Comment by k-one-o-two** [comment]
my package.json
```
{
  "name": "test-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "flow-bin": "^0.61.0",
    "rxjs": "^5.4.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.2.7",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "flow-remove-types": "^1.2.3",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
```
there's no random-js in it

**Comment by GAntoine** [comment]
Great, thank you. Could you try running `flow-typed install` and paste the output here?

**Comment by k-one-o-two** [comment]
@GAntoine I've made a clean project and still get the same:
```
$ flow-typed install
• Found 16 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
ERROR: Unable to rebase the local cache repo. Error rebasing the `master` branch of the following repo:
C:\Users\user\.flow-typed\repo

undefined

NOTE: Unable to rebase local cache! If you don't currently have internet connectivity, no worries -- we'll update the local cache the next time you do.

UNCAUGHT ERROR: Error: npm/random-js_v1.x.x: No libdef files found!
    at validationError (c:\Users\user\AppData\Local\Yarn\config\global\node_modules\flow-typed\dist\lib\validationErrors.js:14:11)
    at extractLibDefsFromNpmPkgDir$ (c:\Users\user\AppData\Local\Yarn\config\global\node_modules\flow-typed\dist\lib\npm\npmLibDefs.js:142:51)
    at tryCatch (c:\Users\user\AppData\Local\Yarn\config\global\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (c:\Users\user\AppData\Local\Yarn\config\global\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (c:\Users\user\AppData\Local\Yarn\config\global\node_modules\regenerator-runtime\runtime.js:117:21)
    at tryCatch (c:\Users\user\AppData\Local\Yarn\config\global\node_modules\regenerator-runtime\runtime.js:65:40)
    at invoke (c:\Users\user\AppData\Local\Yarn\config\global\node_modules\regenerator-runtime\runtime.js:155:20)
    at c:\Users\user\AppData\Local\Yarn\config\global\node_modules\regenerator-runtime\runtime.js:165:13
    at <anonymous>
```

**Comment by JeremyCraigMartinez** [comment]
I fixed this issue by removing `flow-typed` (was using `v2.3.0`) and installing `v2.4.0`

**Comment by k7n4n5t3w4rt** [comment]
Sadly, removing and reinstalling v2.4.0 did not fix the problem for me.

```
$ flow-typed install
• Found 21 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
ERROR: Unable to rebase the local cache repo. Error rebasing the `master` branch of the following repo:
/Users/kynan/.flow-typed/repo

undefined

NOTE: Unable to rebase local cache! If you don't currently have internet connectivity, no worries -- we'll update the local cache the next time you do.
```

**Comment by AndrewSouthpaw** [comment]
The `/Users/kynan/.flow-typed/repo` part looks pretty strange to me, what's going on in your `.flow-typed` directory? What happens if you wipe that folder? Obviously not an actual solution, but I'm curious to see what's going on...

**Comment by wang1212** [comment]
I solved this problem in the following way：

1. Delete all files in the **.flow-typed** folder;
2. Re-run **flow-typed install**

Then, I waited a few minutes for the execution to be successful.

I guess the cause of this problem is the bad network condition.
